version: "3"

services:
  backend-nestjs:
    build: .
    hostname: backend-nestjs
    container_name: backend-nestjs
    restart: unless-stopped
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    expose:
      - 3000